version: '3.7'
services:
  app:
    build:
      context: ./app
      args: 
        RUNTIME_IMAGE_TAG: 5.0-focal-arm32v7
        RUNTIME_ID: linux-arm
    environment:
      DEBUG: "true"
    ports:
      - "5000:5000"
  chrome:
    image: browserless/chrome:1.42.0-chrome-stable
    ports:
      - "3001:3000"
