version: '3.7'
services: 
  web-app:
    build:
      context: web-app
      args:
        RUNTIME_IMAGE: nginx:1.17-alpine
        APP_SCHEME: http
        APP_HOST: localhost
        APP_PORT: 8080
        GRAPHQL_SCHEME: http
        GRAPHQL_HOST: localhost
        GRAPHQL_PORT: 4000
    ports: 
      - "8080:8080"
  graphql-api:
    build:
      context: graphql-api
    ports:
      - "4000:4000"
    environment: 
      DEBUG: "true"
      SECRETS_DIR: /var/secrets
      SEQ_SCHEME: http
      SEQ_HOST: seq
      SEQ_PORT: 5341
  seq:
    image: datalust/seq:5.1
    ports:
      - "5341:80"
    environment: 
      ACCEPT_EULA: "Y"