version: '3.7'
services: 
  web-app:
    build:
      context: web-app
      dockerfile: deploy/Dockerfile
      args:
        RUNTIME_IMAGE: nginx:1.17-alpine
        REACT_APP_GRAPHQL_SCHEME: http
        REACT_APP_GRAPHQL_HOST: localhost
        REACT_APP_GRAPHQL_PORT: 4000
    ports: 
      - "8080:8080"
  graphql:
    build:
      context: graphql
      dockerfile: deploy/Dockerfile
      args: 
        RUNTIME: linux-musl-x64
        RUNTIME_IMAGE: mcr.microsoft.com/dotnet/core/runtime-deps:3.1-alpine
    ports:
      - "4000:4000"
    environment: 
      SECRETS_DIR: /var/secrets
      SEQ_SCHEME: http
      SEQ_HOST: seq
      SEQ_PORT: 5341
    volumes:
      - c:/dev/secrets/ameier38/airtable:/var/secrets/airtable
  seq:
    image: datalust/seq:5.1
    ports:
      - "5341:80"
    environment: 
      ACCEPT_EULA: "Y"