version: '3.8'
services:
  app:
    build:
      context: .
      args: 
        RUNTIME_ID: linux-x64
    environment:
      APP_ENV: dev
      NOTION_DATABASE_ID:
      NOTION_TOKEN:
    ports:
      - 5000:5000
