version: '3.8'
services:
  app:
    build:
      context: .
      args: 
        RUNTIME_ID: linux-x64
    environment:
      DEBUG: 'true'
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_Kestrel__Certificates__Default__Path: /var/certs/localhost.pfx
      ASPNETCORE_Kestrel__Certificates__Default__Password: changeit
      APP_ENV: prod
      NOTION_DATABASE_ID:
      NOTION_TOKEN:
    ports:
      - 5000:5000
    volumes:
      - ./certs:/var/certs
