version: '3.7'
services:
  app:
    build: .
    environment:
      DEBUG: "true"
    ports:
      - "5000:5000"
  chrome:
    image: browserless/chrome:1.42.0-chrome-stable
    ports:
      - "3001:3000"
