version: '3.7'
services:
  app:
    build:
      context: .
      dockerfile: docker/app.Dockerfile
      args: 
        RUNTIME_IMAGE_TAG: 5.0
        RUNTIME_ID: linux-x64
    environment:
      DEBUG: "true"
      CI: "true"
    ports:
      - "5000:5000"
  chrome:
    image: browserless/chrome
    ports:
      - "3001:3000"
  integration-tests:
    build:
      context: .
      dockerfile: docker/integration-tests.Dockerfile
      args: 
        RUNTIME_IMAGE_TAG: 5.0
        RUNTIME_ID: linux-x64
    environment:
      SCREENSHOT_DIR: /var/screenshots
      CLIENT_HOST: app
      CLIENT_PORT: 5000
      CHROME_HOST: chrome
      CHROME_PORT: 3000
    volumes:
      - ./.screenshots:/var/screenshots
    depends_on:
      - app
      - chrome
