name: Merge
on:
  push:
    paths-ignore:
      - '**.md'
    branches:
      - main
jobs:
  up:
    name: Update
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v2
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: us-east-1
          role-to-assume: arn:aws:iam::400689721046:role/blog-deployer
          role-session-name: github
      - name: Start Tunnel
        run: |
          docker run \
            -d \
            -p 1234:1234 \
            cloudflare/cloudflared:2022.3.4 \
            access tcp \
              --hostname=k8s.andrewmeier.dev \
              --url=0.0.0.0:1234 \
              --id=${{ secrets.TUNNEL_SERVICE_TOKEN_ID }} \
              --secret=${{ secrets.TUNNEL_SERVICE_TOKEN_SECRET }}
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 16.x
      - name: Install Packages
        run: npm install
        working-directory: ./pulumi
      - name: Update
        uses: pulumi/actions@v3
        with:
          work-dir: ./pulumi
          command: up
          stack-name: prod
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
