name: Pull Request
on:
  - pull_request
jobs:
  preview:
    name: Preview
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Start Server
        working-directory: ./app
        run: docker-compose up -d app
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '5.0.x'
      - name: Restore Tools and Packages 
        working-directory: ./app
        run: |
          dotnet tool restore
          dotnet paket install
          dotnet paket restore
      - name: Run Unit Tests
        working-directory: ./app
        run: ./fake.sh TestUnits
      - name: Run Integration Tests
        working-directory: ./app
        run: ./fake.sh TestIntegrationsHeadless
      - name: Upload screenshots
        uses: actions/upload-artifact@v2
        with:
          name: screenshots
          path: ./app/.screenshots/*.jpg
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: Install Packages
        run: npm install
        working-directory: ./pulumi
      - name: Preview
        uses: pulumi/actions@v3
        with:
          work-dir: ./pulumi
          command: preview
          stack-name: prod
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
