name: Pull Request
on:
  pull_request:
    paths-ignore:
      - '**.md'
jobs:
  preview:
    name: Preview
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
      pull-requests: write
    steps:
      - uses: actions/checkout@v2
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: us-east-1
          role-to-assume: arn:aws:iam::400689721046:role/blog-deployer
          role-session-name: github
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 16.x
      - name: Install Packages
        run: npm install
        working-directory: ./pulumi
      - name: Preview
        uses: pulumi/actions@v3
        with:
          work-dir: ./pulumi
          command: preview
          stack-name: prod
          diff: true
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
