name: Pull Request
on:
  - pull_request
jobs:
  preview:
    name: Preview
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: Run Integration Tests
        working-directory: ./app
        run: |
          docker-compose build
          docker-compose up -d app chrome
          docker-compose run --rm integration-tests
      - uses: docker://pulumi/actions
        with:
          args: preview
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
          PULUMI_ROOT: pulumi
          PULUMI_CI: pr
