apiVersion: v1
kind: Service
metadata:
  name: {{ include "base-service.fullname" . }}
  labels:
    {{- include "base-service.labels" . | nindent 4 }}
spec:
  type: {{ .Values.serviceType }}
  ports:
    {{ if .Values.isGrpc }}
    - port: {{ .Values.servicePort }}
      targetPort: grpc
      protocol: TCP
      name: grpc
    {{ else }}
    - port: {{ .Values.servicePort }}
      targetPort: http
      protocol: TCP
      name: http
    {{ end }}
  selector:
    {{- include "base-service.selectorLabels" . | nindent 4 }}
